version: '3'

services:
  db:
    image: postgres
    container_name: postgres_for_apache
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./postgre_datadir:/var/lib/postgresql/data"
  apache:
    image: shutovds/django-apach-pgsql-example:patr1    
    restart: always
    environment:
      APACHE_LOCK_DIR: "/tmp"
      APACHE_PID_FILE: "/var/run/apache2/apache.pid"
      APACHE_LOG_DIR: "/var/log/apache"
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"
      APACHE_RUN_DIR: "/var/run/apache2"
      PIPENV_VENV_IN_PROJECT: "true"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    volumes:
      - "./apache/www:/var/www"
      - "./apache/apache2:/etc/apache2"
      - "./apache/log:/var/log/apache2"
      - "./mycode:/home/www-site/project/"
    ports:
      - 8080:80
      - 443:443
      - 8000:8000
    depends_on:
      - db

